- name: 1.1.1.1 Create cis conf file /etc/modprobe.d/cis.conf
  become: true
  template:
    src: cis.conf.j2
    dest: /etc/modprobe.d/cis.conf
    owner: root
    group: root
    mode: 0644

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install cramfs /bin/true'
    state: present

- name: Ensure mounting of freevxfs filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install freevxfs /bin/true'
    state: present

- name: Ensure mounting of jffs2 filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install jffs2 /bin/true'
    state: present

- name: 1.1.1.2 Ensure mounting of hfs filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install hfs /bin/true'
    state: present

- name: 1.1.1.3 Ensure mounting of hfsplus filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install hfsplus /bin/true'
    state: present

- name: 1.1.1.4 Ensure mounting of squashfs filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install squashfs /bin/true'
    state: present

- name: 1.1.1.5 Ensure mounting of udf filesystems is disabled
  become: true
  modprobe:
    name: udf
    state: absent

- name: Ensure mounting of FAT filesystems is disabled
  become: true
  lineinfile:
    path: /etc/modprobe.d/cis.conf
    line: 'install vfat /bin/true'
    state: present

- name: 1.1.17 Ensure noexec option set on /dev/shm partition
  become: true
  mount:
    fstype: tmpfs
    name: "/dev/shm"
    opts: "defaults,nodev,nosuid,noexec"
    src: tmpfs
    state: mounted

- name: 1.1.18 Ensure sticky bit is set on all world-writable directories
  become: true
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t"
  ignore_errors: yes # in case nothing found and input to xargs is empty

- name: 1.1.19 Disable Automounting
  become: true
  shell: "systemctl disable autofs"
  ignore_errors: yes # in case nothing found and input to xargs is empty
  when:
    - ansible_facts['system_vendor'] == "Amazon EC2"

- name: 1.3.1 Ensure AIDE is installed
  become: true
  yum:
    name: aide
    state: latest

- name: 1.3.2 Ensure filesystem integrity is regularly checked - once a day
  become: true
  cron:
    name: "run aide"
    job: "/usr/sbin/aide --check"
    hour: 5
    minute: 0

- name: 1.4.1 Ensure permissions on bootloader config are configured
  become: true
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: og-rwx
    state: touch
  with_items:
    - /boot/grub2/user.cfg
    - /boot/grub2/grub.cfg
  ignore_errors: yes

- name: 1.5.1 Make sure /etc/security/limits.conf set to * hard core 0
  become: true
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^[*]'
    state: present
    line: '* hard core 0'
    backup: no

- name: 1.7.1.2 Write a new /etc/issue
  become: true
  template:
    src: issue.j2
    dest: /etc/issue

- name: 1.7.1.3 Write a new /etc/issue.net
  become: true
  template:
    src: issue.net.j2
    dest: /etc/issue.net