---
- name: 6.1.2 Ensure permissions on /etc/passwd are configured
  become: true
  file:
    path: /etc/passwd
    owner: root
    group: root
    mode: 0644

- name: 6.1.3 Ensure permissions on /etc/shadow are configured
  become: true
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0000

- name: 6.1.4 Ensure permissions on /etc/group are configured
  become: true
  file:
    path: /etc/group
    owner: root
    group: root
    mode: 0644

- name: 6.1.5 Ensure permissions on /etc/gshadow are configured
  become: true
  file:
    path: /etc/gshadow
    owner: root
    group: root
    mode: 0000

- name: 6.1.6 Ensure permissions on /etc/passwd- are configured
  become: true
  file:
    path: /etc/passwd-
    owner: root
    group: root
    mode: 0600

- name: 6.1.7 Ensure permissions on /etc/shadow- are configured
  become: true
  file:
    path: /etc/shadow-
    owner: root
    group: root
    mode: 0000

- name: 6.1.8 Ensure permissions on /etc/group- are configured
  become: true
  file:
    path: /etc/group-
    owner: root
    group: root
    mode: 0600

- name: 6.1.9 Ensure permissions on /etc/gshadow- are configured
  become: true
  file:
    path: /etc/gshadow-
    owner: root
    group: root
    mode: 0000

- name: 6.1.10 Ensure no world writable files exist
  become: true
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod o-w"
  ignore_errors: yes # in case nothing found and input to xargs is empty

- name: 6.2.2 Ensure no legacy "+" entries exist in /etc/passwd
  become: true
  lineinfile:
    path: /etc/passwd
    state: absent
    regexp: '^\+:'

- name: 6.2.3 Ensure no legacy "+" entries exist in /etc/shadow
  become: true
  lineinfile:
    path: /etc/shadow
    state: absent
    regexp: '^\+:'

- name: 6.2.4 Ensure no legacy "+" entries exist in /etc/group
  become: true
  lineinfile:
    path: /etc/group
    state: absent
    regexp: '^\+:'

- name: 6.2.6 Ensure root PATH Integrity
  become: true
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: '0700'
